apiVersion: v1
kind: Service
metadata:
   name: {{.Release.Name}}-db-service
   labels:
     app: db
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: {{.Values.service.dbPort}}
      targetPort: {{.Values.service.dbPort}}