apiVersion: v1
kind: Service
metadata:
  name: app-external-service
  labels:
    app: url-shortener
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: url-shortener
