apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-app
  labels:
    app: url-shortener
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener-app
          image: maverick8738/url-shortener:latest
          ports:
          - containerPort: 8080
          env:
            - name: DB_HOST
              value: "db-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "root"
            - name: DB_NAME
              value: "url_mappings"