name: Golang

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Files
        run: ls -la

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Download Dependencies
        run: go mod tidy && go mod download

      - name: Build
        run: go build -o url-shortener ./api-services/main.go


      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the image
        run: docker build -t maverick8738/url-shortener:latest .

      - name: Push the image
        run: docker push maverick8738/url-shortener:latest

      - name: AWS Login
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

      - name : Install kubectl for K8s
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin

      - name: Install Docker
        run: |
          sudo yum install wget curl -y
          curl -fsSL https://get.docker.com | sh
          sudo apt-get update
          sudo systemctl start docker
          sudo systemctl enable docker


      - name: Deployment
        run: kubectl apply -f ./kubernetes

      - name: Kube config
        run: aws eks --region us-west-2 update-kubeconfig --name url-shortener

